stages:
  - build
  - unit_test
  - integration_test


# variables:
#   GIT_STRATEGY: none  # Disable automatic Git clone

# before_script:
#   - rm -rf /home/gitlab-runner/builds/*
#   - pkill -f ci_example
#   - pkill -f ci_mock_server

build-job:
  stage: build
  script:
    - go mod tidy
    - go vet ./...
    - go build -o ci_example main.go
  after_script:
    - rm -rf $(pwd)/*
    - rm -rf $(pwd)/.git*
  only:
    - master
    - merge_requests

unit-test-job:
  stage: unit_test
  needs: ["build-job"]
  script:
    - EXCLUDE_DIRS="tests"
    - TEST_DIRS=$(go list ./... | grep -vE $(echo $EXCLUDE_DIRS | sed 's/ /|/g'))
    - go test -v -timeout 2m $TEST_DIRS
  after_script:
    - rm -rf $(pwd)/*
    - rm -rf $(pwd)/.git*
  only:
    - master
    - merge_requests

integration-test-job:
  stage: integration_test
  needs: ["unit-test-job"]
  script:
    - go build -o ci_mock_server tests/mock_server/main.go
    - go build -o ci_example main.go
    - ./ci_mock_server &
    - ./ci_example &
    - sleep 3
    - go test -v -timeout 5m ./tests
  after_script:
    - pkill -f ci_example
    - pkill -f ci_mock_server
    - rm -rf $(pwd)/*
    - rm -rf $(pwd)/.git*
  only:
    - master
    - merge_requests