name: Go CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build Project
        run: |
          go mod tidy
          go vet ./...
          go build -o bin/ci_example main.go

      - name: Run Unit Tests
        run: |
          EXCLUDE_DIRS="tests"
          TEST_DIRS=$(go list ./... | grep -vE $(echo $EXCLUDE_DIRS | sed 's/ /|/g'))
          go test -v $TEST_DIRS